name: Base

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
